version: '3.9'

services:
  server:
    container_name: server
    build:
      context: ./be
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - '${BE_PORT}:${BE_PORT}'
    environment:
      - BE_PORT=${BE_PORT}
    volumes:
      - ./be:/app
      - /be/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - PORT=${DB_PORT}
    env_file:
      - ./.env
    networks:
      - backend

  fe:
    container_name: fe
    build:
      context: ./fe
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./fe:/app
      - /app/node_modules
    ports:
      - '${FE_PORT}:${FE_PORT}'
    environment:
      - PORT=${FE_PORT}
    restart: 'unless-stopped'
    networks:
      - backend

  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
    depends_on:
      - server
      - fe

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
